#!/usr/bin/env python3
"""
Compose Compiler Metrics & Reports Parser.

Parses JSON and text reports generated by Jetpack Compose compiler:
- <module>-module.json
- <module>-classes.txt
- <module>-composables.txt

Outputs a Markdown table summarizing skippability and stability rates,
and outputs unstable classes for inspection.
"""

import os
import sys
import glob
import json

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
METRICS_DIR = os.path.join(REPO_ROOT, "app", "build", "compose_metrics")
REPORTS_DIR = os.path.join(REPO_ROOT, "app", "build", "compose_reports")

def parse_metrics():
    json_files = glob.glob(os.path.join(METRICS_DIR, "*-module.json"))
    if not json_files:
        print(f"Warning: No *-module.json found in {METRICS_DIR}")
        return None

    with open(json_files[0], "r", encoding="utf-8") as f:
        data = json.load(f)
    return data

def parse_unstable_classes():
    classes_files = glob.glob(os.path.join(REPORTS_DIR, "*-classes.txt"))
    if not classes_files:
        return []

    unstable = []
    with open(classes_files[0], "r", encoding="utf-8") as f:
        content = f.read()

    for block in content.split("\n\n"):
        if block.startswith("unstable class"):
            lines = block.strip().split("\n")
            class_name = lines[0].replace("unstable class", "").strip()
            unstable.append(class_name)

    return unstable

def generate_markdown(data, unstable_classes):
    skippable = data.get("skippableComposables", 0)
    restartable = data.get("restartableComposables", 0)
    total_composables = data.get("totalComposables", 0)
    stable_classes = data.get("stableClasses", 0)
    unstable_count = data.get("unstableClasses", 0)
    total_classes = data.get("totalClasses", 0)

    skippable_pct = (skippable / restartable * 100) if restartable > 0 else 0
    stable_pct = (stable_classes / total_classes * 100) if total_classes > 0 else 0

    md = []
    md.append("## 🎨 Compose Compiler Stability & Metrics Report\n")
    md.append("| Metric | Count | Rate |")
    md.append("|---|---|---|")
    md.append(f"| **Skippable Composables** | `{skippable} / {restartable}` | **{skippable_pct:.1f}%** |")
    md.append(f"| **Restartable Composables** | `{restartable} / {total_composables}` | - |")
    md.append(f"| **Stable Classes** | `{stable_classes} / {total_classes}` | **{stable_pct:.1f}%** |")
    md.append(f"| **Unstable Classes** | `{unstable_count}` | - |\n")

    if unstable_classes:
        md.append("<details><summary><b>View Unstable Classes (" + str(len(unstable_classes)) + ")</b></summary>\n")
        md.append("```text")
        for cls in unstable_classes[:30]:
            md.append(cls)
        if len(unstable_classes) > 30:
            md.append(f"... and {len(unstable_classes) - 30} more")
        md.append("```\n</details>\n")

    md.append("> 💡 **Tip:** Skippable Composable functions allow Jetpack Compose to skip recomposition when input parameters have not changed, eliminating UI jank and saving CPU cycles.\n")
    return "\n".join(md)

def main():
    data = parse_metrics()
    if not data:
        print("No Compose metrics data available to report.")
        sys.exit(0)

    unstable_classes = parse_unstable_classes()
    markdown_output = generate_markdown(data, unstable_classes)
    print(markdown_output)

    # If GITHUB_STEP_SUMMARY environment variable exists, write report
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary_path and os.path.exists(os.path.dirname(summary_path)):
        with open(summary_path, "a", encoding="utf-8") as f:
            f.write(markdown_output)
        print("Successfully written to GITHUB_STEP_SUMMARY.")

if __name__ == "__main__":
    main()
